services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - 4000:5050
      - 9229:9229
    command: npm run start:migrate:dev
    depends_on:
      - db
    networks:
      - app_network
    restart: always

  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.postgres
    env_file:
      - .env.docker
    ports:
      - 5433:5432
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_logs:/var/log/postgresql
    networks:
      - app_network
    restart: always

volumes:
  pg_data:
  pg_logs:


networks:
  app_network:
    driver: bridge
